ceicaperu/urls.py
from django.contrib import admin, sitemaps
from django.urls import path
from django.urls import include, reverse
from django.http import HttpResponse
from . import views
from . import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from django.utils.translation import ugettext_lazy as _
from django.contrib.sitemaps.views import sitemap

class StaticViewSitemap(sitemaps.Sitemap):
    priority = 0.5
    changefreq = 'daily'

    def items(self):
        return ['index', 'courses', 'faqs', 'special-programs', 'extras', 'accommodation', 'prices', 'about-the-school', 'contact', 'why-volunteer', 'volunteer-projects', 'how-to-enroll', 'privacy-policy', 'terms-of-service', 'icons-used', 'enroll', 'application_type', 'volunteer_application', 'volunteer_application_sent', 'enroll_part_two', 'enroll_part_three', 'application_submitted']

    def location(self, item):
        return reverse(item)

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('', RedirectView.as_view(url='/en/')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
             name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain"))
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    url(_(r'^enroll/'), include('enroll.urls')),
    path('', views.index, name='index'),
    url(_(r'courses/$'), views.LevelsListView.as_view(), name='courses'),
    url(_(r'^faqs/$'), views.FAQListView.as_view(), name='faqs'),
    url(_(r'^special-programs/$'), views.SpecialProgramListView.as_view(), name='special-programs'),
    url(_(r'^extras/$'), views.ExtrasListView.as_view(), name='extras'),
    url(_(r'^accommodation/$'), views.AccommodationListView.as_view(), name='accommodation'),
    url(_(r'^prices/$'), views.PriceListView.as_view(), name='prices'),
    url(_(r'^about-the-school/$'), views.TeacherListView.as_view(), name='about-the-school'),
    url(_(r'^contact/$'), views.contact, name='contact'),
    url(_(r'^why-volunteer/$'), views.whyvolunteer, name='why-volunteer'),
    url(_(r'^volunteer-projects/$'), views.VolunteerProjectListView.as_view(), name='volunteer-projects'),
    url(_(r'^how-to-enroll/$'), views.howtoenroll, name="how-to-enroll"),
    url(_(r'^privacy-policy/$'), views.privacypolicy, name='privacy-policy'),
    url(_(r'^terms-of-service/$'), views.termsofservice, name='terms-of-service'),
    url(_(r'^icons-used/$'), views.iconsused, name='icons-used'),
)



from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

enroll/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.EnrollPartOne, name="enroll"),
    path('application_type', views.EnrollApplicationType, name="application_type"),
    path('volunteer_application', views.VolunteerApplicationPage, name="volunteer_application"),
    path('volunteer_application_sent', views.VolunteerApplicationSent, name="volunteer_application_sent"),
    path('part_two', views.EnrollPartTwo, name="enroll_part_two"),
    path('part_three', views.EnrollPartThree, name="enroll_part_three"),
    path('test', views.Test, name="test"),
    path('application_submitted', views.ApplicationSubmitted, name="application_submitted"),
]

enroll/models.py
from django.db import models
from django.forms import ModelForm
import datetime
from django import forms
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Customer(models.Model):
    # Fields
    first_name = models.CharField(max_length=30, verbose_name=_('first_name'))
    last_name = models.CharField(max_length=30, verbose_name=_('last_name'))
    email_address = models.EmailField(max_length=254, verbose_name=_('email_address'))
    phone = models.CharField(max_length=15, verbose_name=_('phone'))
    whatsapp = models.CharField(max_length=15, blank=True, verbose_name=_('whatsapp'))
    nationality = models.CharField(max_length=15, verbose_name=_('nationality'))
    passport_number = models.CharField(max_length=12, verbose_name=_('passport_number'))
    occupation = models.CharField(max_length = 30, blank=True, verbose_name=_('occupation'))
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False, default=datetime.date.today, verbose_name=_('date_of_birth'))
    emergency_name = models.CharField(max_length = 60)
    emergency_number = models.CharField(max_length = 15)

    GENDERS = (
        ('m', _('Male')),
        ('f', _('Female')),
        ('o', _('Other')),
        ('p', _('Prefer not to say')),
    )

    MARITAL_STATUSES = (
        ('m', _('Married')),
        ('s', _('Single')),
    )

    gender = models.CharField(max_length=1, choices=GENDERS, blank=True, verbose_name=_('gender'))
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUSES, blank=True, verbose_name=_('marital_status'))

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def display_full_name(self):
        return self.first_name + ' ' + self.last_name
    display_full_name.short_description = 'Full name'

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['emergency_name', 'emergency_number']


class Service(models.Model):
    #fields
    service_name = models.CharField(max_length=60)
    service_description = models.TextField(max_length=2000, blank=True, null=True)
    levels_open_to = models.ManyToManyField('AbilityLevel')
    image = models.ImageField(upload_to='services/', null=True, blank=True)
    fixed_duration = models.BooleanField(default = False)
    duration_weeks = models.PositiveSmallIntegerField(default = 1, help_text = "Ignore if duration is not fixed")
    hours = models.PositiveSmallIntegerField(default = 10, help_text = "If duration is not fixed, put in hours per week")
    service_type = models.CharField(max_length=60)

    @property
    def daily_hours(self):
        return int(self.hours / 5)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.service_name

    def display_first_price(self):
        price_list_display = ''
        for e in Price.objects.filter(service=self):
            price_list_display += str(e.customer_type) + ": S" + str(e.price) + "  |  "
        return price_list_display
    display_first_price.short_description = 'Prices'


class AbilityLevel(models.Model):
    #fields
    level_name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='levels/', null=True)
    level_description = models.TextField(max_length=2000, blank=True, null=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.level_name

class VolunteerProject(models.Model):
    #fields
    project_name = models.CharField(max_length=45)
    image = models.ImageField(upload_to='projects/', null=True)
    description = models.TextField(max_length=2000, blank=True, null=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.project_name

class VolunteerProgram(models.Model):
    name = models.CharField(max_length=30)

    program_type = models.CharField(max_length=30)
    orientation = models.CharField(max_length=50)
    spanish_lessons = models.CharField(max_length=50, null=True, blank=True)
    volunteer_work = models.CharField(max_length=50, null=False, blank=True, default="None")
    accommodation = models.CharField(max_length=50)
    price = models.DecimalField(default=0, max_digits=7, decimal_places=2)

    def __str__(self):
        return self.name + " - " + self.program_type

class VolunteerApplication(models.Model):
    #Fields
    DEFAULT_PROGRAM_ID = 1

    applicant = models.ForeignKey('Customer', on_delete=models.SET_NULL, null=True)
    program_chosen = models.ForeignKey('VolunteerProgram', on_delete=models.SET_NULL, null=True, default=DEFAULT_PROGRAM_ID)
    #first_preference = models.CharField(max_length = 40, default="none")
    #second_preference = models.CharField(max_length = 40, default="none")
    #third_preference = models.CharField(max_length = 40, default="none")
    preferences = models.CharField(max_length = 150, default="No preferences given")
    course_start_date = models.DateField(auto_now=False, auto_now_add=False)

    application_made = models.DateField(auto_now=True, auto_now_add=False)

    STATUS = (
        ('s', 'Submitted'),
        ('a', 'Accepted')
    )
    status = models.CharField(max_length=1, choices=STATUS, default='s')

    def __init__(self, *args, **kwargs):
        super(VolunteerApplication, self).__init__(*args, **kwargs)
        self.__original_status = self.status

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.status != self.__original_status:
            if self.status == 'a':
                send_mail(
                    'Subject here',
                    'Dear ' + self.applicant.first_name + ", \n\n We're pleased to confirm that your volunteering application has been accepted. Please complete your enrollment by clicking the link below and choosing your accommodation: \n\nhttp://127.0.0.1:8000/en/enroll/part_three?q=" + self.applicant.email_address + "\n\nHasta pronto!\nThe Ceica Peru Team",
                    'ceicaperuspanishschool@hotmail.com',
                    [self.applicant.email_address],
                    fail_silently=False,
                    html_message = 'Dear ' + self.applicant.first_name + ", \n\n We're pleased to confirm that your volunteering application has been accepted. Please complete your enrollment by clicking the link below and choosing your accommodation: \n\n<a href='http://127.0.0.1:8000/en/enroll/part_three?q=" + self.applicant.email_address + "'>Complete enrollment</a>\n\nHasta pronto!\nThe Ceica Peru Team",
                )
        super(VolunteerApplication, self).save(force_insert, force_update, *args, **kwargs)
        self.__original_status = self.status


    def __str__(self):
        return '{0} - {1} (Starting {2})'.format(self.applicant, self.program_chosen, self.course_start_date)

    class Meta:
        ordering = ['-application_made']

    def total_price(self):
        program_price = self.program_chosen.price
        return 'S{0}'.format(program_price)

class TextInput(forms.TextInput):
    input_type = "text"

class VolunteerApplicationForm(ModelForm):
    first_preference = forms.ModelChoiceField(queryset=VolunteerProject.objects.all(), empty_label=None, widget = forms.RadioSelect())
    second_preference = forms.ModelChoiceField(queryset=VolunteerProject.objects.all(), empty_label=None, widget = forms.RadioSelect())
    third_preference = forms.ModelChoiceField(queryset=VolunteerProject.objects.all(), empty_label=None, widget = forms.RadioSelect())
    class Meta:
        model = VolunteerApplication
        fields = '__all__'
        exclude = ['application_made']
        widgets = {
            'program_chosen': forms.RadioSelect(),
            'applicant': TextInput(attrs={'readonly': True})
        }


class Price(models.Model):
    #fields
    service = models.ForeignKey('Service', on_delete=models.SET_NULL, null=True)
    customer_type = models.ForeignKey('CustomerType', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(default=0, max_digits=7, decimal_places=2)

    def __str__(self):
        return '{0} - {1}'.format(self.service, self.customer_type)

    class Meta:
        ordering = ['service', 'customer_type']

class CustomerType(models.Model):
    #Fields
    number = models.PositiveSmallIntegerField(default=1)

    AGES = (
        ('s', 'Student'),
        ('a', 'Adult'),
        ('c', 'Child'),
    )

    age = models.CharField(max_length=1, choices=AGES)

    def __str__(self):
        return '{0} - group of {1}'.format(self.get_age_display(), self.number)

class CourseApplication(models.Model):
    #Fields
    DEFAULT_COURSE_ID = 1

    applicant = models.ForeignKey('Customer', on_delete=models.SET_NULL, null=True)
    course_chosen = models.ForeignKey('Service', on_delete=models.SET_NULL, null=True, default=DEFAULT_COURSE_ID)
    course_start_date = models.DateField(auto_now=False, auto_now_add=False)
    course_length = models.PositiveSmallIntegerField(default=1)

    GROUPNUMBER = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, _("4 or more")),
    )

    SPANISHLEVEL = (
        ("b", _("Beginner")),
        ("i", _("Intermediate")),
        ("a", _("Advanced")),
        ("d", _("Different levels")),
    )

    current_spanish_level = models.CharField(max_length=1, choices=SPANISHLEVEL, default="b")
    group_number = models.PositiveSmallIntegerField(default=1, choices=GROUPNUMBER)
    application_made = models.DateField(auto_now=True, auto_now_add=False)


    def __str__(self):
        return '{0} - {1} (Starting {2})'.format(self.applicant, self.course_chosen, self.course_start_date)

    class Meta:
        ordering = ['-application_made']

    def total_price(self):

ceicaperu/templates/courses.html
{% extends "template.html" %}
{% load i18n %}
{% block title %}{% trans "Spanish lessons: beginner to advanced | Ceica Peru Spanish School" %}{% endblock %}
{% block metadescription %}<meta name="description" content="{% trans 'Ceica Peru offers Spanish lessons for all ability levels in our sunny garden. We also offer flexible schedules from easy-going to intensive courses.' %}">{% endblock %}
{% block content %}
{% load static %}

<header class="full-width ">
  <div class="full-width-title-image">
    <picture>
      <source media="(max-width: 799px)" srcset=" {% static 'images/learn-spanish-800.JPG' %}">
      <source media="(min-width: 800px)" srcset=" {% static 'images/learn-spanish-1600.JPG' %}">
      <img src=" {% static 'images/learn-spanish-1600.JPG' %}" alt="{% trans 'Student learning Spanish in our garden' %}">
    </picture>

    <div class="title-image-text">
      <h1 class="slider-title">{% trans 'Spanish Lessons' %}</h1>
    </div>
  </div>
</header>
<div class="container two-column">


  <main class="col col-2-3">
    <p>{% trans 'Ceica Peru Spanish School has the Spanish course you need because all our courses are  tailor-made to suit the ability and needs of our students. You decide what day to start your course, the number of hours to study (at least 10 hours per week) and the duration of the course. Lessons are normally held from Monday to Friday, but lessons during the weekend are also possible.' %}</p>
    {% if abilitylevel_list %}
    <h2>{% trans 'Ability levels' %}</h2>
    {% for abilitylevel in abilitylevel_list %}
    <button class="accordion">{{abilitylevel.level_name }}<i class="fas fa-angle-down fa-lg style="float:right""></i></button>

    <div class="panel">
      <div class="col col-1-3"><img class="photo" src="/static/uploads/{{abilitylevel.image}}" alt="{% trans 'Class' %} - {{abilitylevel.level_name}}"></div>
      <div class="col col-2-3"><p>{{abilitylevel.level_description|linebreaksbr}}</p></div>

    </div>
    {% endfor %}
    {% else %}
    <p>{% trans 'No courses, sorry!' %}</p>
    {% endif %}
    <br>
    {% if price_list %}
    <section class="single-column">
    <h2>{% trans 'Prices' %}</h2>
    <div class="responsive-table">
      <table class="price-list">
        <tr>
          <th>{% trans "(Price per person)" %}
          </th>

      {% for customer_type in customer_type_list %}
        {% if customer_type.number == 4 %}
        <th>{% trans 'Group of 4 or more ' %}</th>
        {% elif customer_type.number == 1 %}
        <th>{% trans 'One on one' %}</th>
        {% else %}
        <th>{% trans 'Group of' %} {{ customer_type.number}}</th>
        {% endif %}
      {% endfor %}
        </tr>
        {% regroup price_list by service as lesson_list %}
        {% for service, prices in lesson_list %}
        <tr>
          <td>{{service}}
          </td>
          {% for customer_type in customer_type_list %}
          <td>{% for price in prices %}{% if price.customer_type == customer_type %}S/.{{ price.price}}{% endif %}{% endfor %}</td>
          {% endfor %}
        {% endfor %}
        </tr>
      </table>
    </diiv>
    <p class="prominent">{% trans 'For more prices and to calculate the total cost of your stay at Ceica Peru,' %}<a href="/prices"> {% trans 'click here' %}</a>.</p>


    {% endif %}

    </section>
  </main>
  <aside class="col col-1-3 key-information">
    <h2 class="aside-header">{% trans 'Course information' %}</h2>
    <ul>
      <li>{% trans 'Lessons evenly divided between grammar and speaking practice' %}</li>
      <li>{% trans 'Each day of lessons includes a 20 minute coffee break' %}</li>
      <li>{% trans 'Coursebook and teaching material provided free of charge' %}</li>
      <li>{% trans 'You will be presented with a certificate at the end of your course' %}</li>
      <li>{% trans 'Maximum of <strong>4 students</strong> in a group' %}</li>

    </ul>
    <a href="{% url 'enroll' %}"><button class="btn">{% trans 'Enroll now' %}</button></a>
  </aside>
</div>
{% endblock %}

ceicaperu/templates/faqs.html
{% extends "template.html" %}
{% load i18n %}
{% block title %}{% trans "FAQs | Ceica Peru Spanish School" %}{% endblock %}
{% block metadescription %}<meta name="description" content="{% trans 'How much can I learn in a week? How do I get to Arequipa? Check out our FAQs and find the answer.' %}">{% endblock %}
{% block content %}
{% load static %}

<header class="full-width">
  <div class="full-width-title-image">
    <picture>
      <source media="(max-width: 799px)" srcset=" {% static 'images/faqs-800.JPG' %}">
      <source media="(min-width: 800px)" srcset=" {% static 'images/faqs-1600.JPG' %}">
      <img src=" {% static 'images/faqs-1600.JPG' %}" alt="{% trans 'Plants in the Ceica Peru school garden' %}">
    </picture>
    <div class="title-image-text">
      <h1 class="slider-title">{% trans 'FAQs' %}</h1>
    </div>
</header>
<section class="container">
{% if object_list %}
  {% regroup object_list by question_type as question_type_list %}
  {% for question_type in question_type_list %}
  <h2 class="text-center"> {{ question_type.grouper }}</h2>
  {% for FAQ in question_type.list %}
  <button class="accordion">{{ FAQ.question }}<i class="fas fa-angle-down fa-lg style="float:right""></i></button>
  <div class="panel faq">
    <p>{{FAQ.answer|linebreaksbr}}</p>


  </div>
  {% endfor %}
  {% endfor %}
{% else %}
<p>{% trans 'No FAQs, sorry!' %}</p>
{% endif %}
</section>
{% endblock %}

ceicaperu/templates/prices.html
{% extends "template.html" %}
{% load i18n %}
{% block title %}{% trans "Prices | Ceica Peru Spanish School" %}{% endblock %}
{% block metadescription %}<meta name="description" content="{% trans 'A full price list for our courses, volunteer programs, extras, and accommodation at Ceica Peru Spanish School.' %}">{% endblock %}
{% block content %}
{% load static %}

<header class="full-width">
  <div class="full-width-title-image">
    <picture>
      <source media="(max-width: 799px)" srcset=" {% static 'images/prices-800.JPG' %}">
      <source media="(min-width: 800px)" srcset=" {% static 'images/prices-1600.JPG' %}">
      <img src=" {% static 'images/prices-1600.JPG' %}" alt="{% trans 'An old street in Arequipa' %}">
    </picture>
    <div class="title-image-text">
      <h1 class="slider-title">{% trans 'Prices' %}</h1>
    </div>
</header>
<div class="container">
  <p class="prominent"><a href="#C">{% trans 'Courses' %}</a> | <a href="#A">{% trans 'Accommodation' %}</a> | <a href="#O">{% trans 'Other' %}</a></p>
</div>
<section class="strips">
{% if price_list %}
  <h2 id="C" class="text-center">{% trans 'Courses' %}</h2>
  <p class="prominent">{% trans 'Prices are shown per week in Soles. Special courses may have a fixed duration (see ' %}<a href="{% url 'special-programs' %}">{% trans 'special programs' %}</a>).</p>
  {% regroup price_list by service.service_type as service_type_list %}
  {% for service_type, prices in service_type_list %}
      <div class="container">
      <h2 id="{{service_type|first}}"> {{ service_type }}</h2>
        <div class="responsive-table">
        <table class="price-list">
          <tr>
            <th>{% trans '(Price per person)' %}
            </th>

        {% for customer_type in customer_type_list %}
          {% if customer_type.number == 4 %}
          <th>{% trans 'Group of 4 or more ' %}</th>
          {% elif customer_type.number == 1 %}
          <th>{% trans 'One on one' %}</th>
          {% else %}
          <th>{% trans 'Group of' %} {{ customer_type.number}}</th>
          {% endif %}
        {% endfor %}
          </tr>
          {% regroup prices by service as service_list %}
          {% for service, prices in service_list %}
          <tr>
            <td>{{service}}
            </td>
            {% for customer_type in customer_type_list %}
            <td>{% for price in prices %}{% if price.customer_type == customer_type %}S/.{{ price.price}}{% endif %}{% endfor %}</td>
            {% endfor %}
          {% endfor %}
          </tr>
        </table>
        </div>
      </div>
  {% endfor %}
{% else %}
<p>{% trans 'No prices, sorry!' %}</p>
{% endif %}
</section>
<section class="strips">
<div class="container">
  <h2 id="A" class="text-center">{% trans 'Accommodation' %}</h2>

  {% if first_price_list %}
  <h2>{% trans 'Host family' %}</h2>
  <div class="responsive-table">
  <table class="price-list">
    <tr>
      <th>{% trans '(Price per room per week)' %}</th>
      {% regroup catering_price_list by catering as catering_type_list %}
      {% for catering_type, prices in catering_type_list %}
      <th>{{catering_type}}</th>
      {% endfor %}
      {% regroup room_price_list by room_type as room_type_list %}
      {% for room_type, the_prices in room_type_list %}
      <tr>

        <td>{{room_type}} {% trans 'room' %}
        </td>
        {% for catering_type in catering_type_list %}
        <td>{% for price in the_prices %}{% if price.catering == catering_type.grouper %}S/.{{ price.price}}{% endif %}{% endfor %}</td>
        {% endfor %}
      {% endfor %}
      </tr>
    </tr>
  </table>
  </div>
  {% endif %}

  {% if second_price_list %}
  <h2>{% trans 'School building' %}</h2>
  <div class="responsive-table">
  <table class="price-list">
    <tr>
      <th>{% trans '(Price per room per week)' %}</th>
      {% regroup school_room_price_list by room_type as room_type_list %}
      {% for room_type, prices in room_type_list %}
      <th>{{room_type}} </th>
      {% endfor %}
      {% regroup school_catering_price_list by catering as catering_type_list %}
      {% for catering_type, the_prices in catering_type_list %}
      <tr>

        <td>{% trans 'Catering' %} - {{catering_type}}
        </td>
        {% for room_type in room_type_list %}
        <td>{% for price in the_prices %}{% if price.room_type == room_type.grouper %}S/.{{ price.price}}0{% endif %}{% endfor %}</td>
        {% endfor %}
      {% endfor %}
      </tr>
    </tr>
  </table>
  </div>
  {% endif %}

  {% if third_price_list %}
  <h2>{% trans 'Private apartment' %}</h2>
  <div class="responsive-table">
  <table class="price-list">
    <tr>
      <th></th>
      {% for duration in third_price_list %}
      <th>{{duration.duration|capfirst}}</th>
      {% endfor %}
    </tr>
    <tr>
      <td>{% trans 'Price' %}</td>
      {% for duration in third_price_list %}
      <td>S/.{{duration.price}}0</td>
      {% endfor %}
    </tr>
  </table>
  </div>
  {% else %}
  Oh no!
  {% endif %}
  <p>{% trans 'A deposit of  450  soles is required to rent an apartment for two weeks. To rent an apartment for a month or more a deposit of 900 soles is required.  The deposit will be returned at the end of the contract if there has been no breakage or damage to the apartment; if there has been either a corresponding deduction of the refund will be made.' %}</p>
</div>
</section>
<section class="strips">
  <div class="container">
    <h2 id="O" class="text-center">{% trans 'Other' %}</h2>
    <p><b>{% trans 'Airport and pickup:' %}</b>  {% trans 'We offer pick-up service for our students, where we charge 35 soles for transportation from the airport or bus station to the host family.' %}</p>
    <p><b>{% trans 'Enrollment and reservation:' %} </b>{% trans 'To book  courses and  accommodation students have to pay the enrollment fee, and complete and send the enrollment form that appears on the "Enroll" page. We request an enrollment fee of US$20 to book a place for a student, and this fee must be paid with a credit card via paypal. The payment of Spanish lessons and accommodation must be paid weekly at the school at the beginning of each week. We only accept cash and we prefer  payment in US dollars or Soles (the local currency).' %}</p>
  </div>
</section>

{% endblock %}

ceicaperu/templates/volunteer-programs.html
{% extends "template.html" %}
{% block content %}
{% load static %}
{% load i18n %}
<header class="full-width ">
  <div class="full-width-title-image title-image-responsive">
    <img src="{% static 'images/volunteer-programs.jpg' %}">
    <div class="title-image-text">
      <h1 class="slider-title"{% trans '>Volunteer Programs' %}</h1>
    </div>
  </div>
</header>
<div class="container two-column">


  <main class="col col-2-3">
    <section class="section">
      <p>{% trans 'Below you will find the list of volunteer projects that Ceica Peru currently offers. You can choose the length of your stay and you can also choose to combine volunteering with Spanish lessons. For more information on this, see the price table at the bottom of the page.' %}</p>
      {% if volunteer_project_list %}
      <h2{% trans '>Volunteer Projects' %}</h2>
      <div class="accordion-set">
        {% for project in volunteer_project_list %}
        <button class="accordion">{{project.project_name }}<i class="fas fa-angle-down fa-lg style="float:right""></i></button>

        <div class="panel">
          <img class="accordion-image" src="/static/uploads/{{project.image}}">

          <p>{{project.description|linebreaksbr}}</p>

        </div>
        {% endfor %}
      </div>
      {% else %}
      <p>{% trans 'No volunteer programs, sorry!' %}</p>
      {% endif %}
    </section>
    <section class="section">
      {% if price_list %}
      <h2>{% trans 'Prices' %}</h2>
      {% regroup price_list by get_program_type_display as program_type_list %}
      {% for program_type, programs in program_type_list %}


          <table class="price-list">
            <tr>
              <th>{{program_type}}</th>
              <th>{% trans 'Orientation' %}</th>
              <th>{% trans 'Volunteering' %}</th>
              <th>{% trans 'Accommodation' %}</th>
              <th>{% trans 'Price' %}</th>
            </tr>
            {% for program in programs %}
            <tr>
              <td>{{program.name}}</td>
              <td>{{program.orientation}}</td>
              <td>{{program.volunteer_work}}</td>
              <td>{{program.accommodation}}</td>
              <td>S/. {{program.price}}</td>
            </tr>
            {% endfor %}
          </table>
          <br>


      {% endfor %}
      <p class="prominent">{% trans 'For more prices and to calculate the total cost of your stay at Ceica Peru' %}, <a href="/prices">{% trans 'click here' %}</a>.</p>


      {% endif %}
    </section>
  </main>
  <aside class="col col-1-3 key-information">
    <h2 class="aside-header">{% trans 'Program requirements' %}</h2>
    <ul>
      <li>{% trans 'You must be at least 18 years old.' %}</li>
      <li>{% trans 'You should obey the personnel in charge of your social project.' %}</li>
      <li>{% trans "It's important to have an open mindset to understand the restrictions that our traditional  conservative culture imposes, for example when you are working wear appropriate clothes (no miniskirts, shorts, low or skimpy tops etc); avoid romantic relationships with the personnel or youths in care." %}</li>
      <li>{% trans 'Behave ethically in the volunteer work place and be willing to comply with the norms established by the institution.' %}</li>

    </ul>
    <a href="{% url 'enroll' %}"><button class="btn">{% trans 'Enrol now' %}</button></a>
  </aside>
</div>
{% endblock %}